version: '3.7'
services:
    hub:
        image: selenium/hub:3.141.59-20200525
        ports:
            - "0.0.0.0:4444:4444"
        networks:
            default:
               ipv4_address: 172.20.0.2

    chrome:
        image: selenium/node-chrome:3.141.59-20200525
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
        networks:
            default:
               ipv4_address: 172.20.0.3

    web:
        build: .
        image: scrapping_sena
        ports:
            - "5000:5000"
        networks:
            default:
               ipv4_address: 172.20.0.4

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
